[project]
name = "sap-gui-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fnxL", email = "48607132+fnxL@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pywinauto>=0.6.9",
]

[build-system]
requires = ["uv_build>=0.8.2,<0.9.0"]
build-backend = "uv_build"
